In [1]:
import espn_api.basketball as bb
import pandas as pd
from datetime import date, timedelta
from os.path import exists

LetsGetTropical = bb.League(
    league_id=1966813226, 
    year=2023,
    espn_s2='AEBxJ8i6hR4erhDR%2B%2F9oCCkZrfl61R6BC%2Fbmzsxh6Dfh2mMe%2BLUXBDPL8WbhdArQ5mXeKF58lWIPSaQeDfK1jCUT%2BgE6TEGw7O8ZGRzoNC8sQ5wD5VUb%2FevTcpAYdBaSk7yRqRKNr41l2jzxgS4M9ZUyh3WvrOP8PQQZQWp%2BvnhuIi3%2F8sJNxRBC0prRQg5whXEfaLKkKdL641IASDuDUISI9%2BlWPj8RSWPO7rvbtsao57Qz%2Bxxybe6D2G5D5%2BXuBD6SFlvHT7kjX%2B81j8OSsjqe', 
    swid='{65841A9D-0A7D-4E82-A2BD-25B825CBF245}'
)

In [7]:
x = LetsGetTropical.free_agents(size=1000)

In [18]:
x[0].position

'PG'

In [2]:
daily_df = []
for team in LetsGetTropical.teams:
    for player in team.roster:
        daily_df.append({
            'game_date': date.today() - timedelta(days=1),
            'team_id': team.team_id,
            'player_id': player.playerId,
            'player_name': player.name,
            'player_team': player.proTeam,
            'player_status': player.injuryStatus,
            'player_team_slot': player.lineupSlot
        }) 

daily_df = pd.DataFrame(daily_df)
if exists('daily.pq'): daily_df = pd.concat([pd.read_parquet('daily.pq'), daily_df])
daily_df.to_parquet('daily.pq')

In [3]:
daily_df

,game_date,team_id,player_id,player_name,player_team,player_status,player_team_slot
0,2022-12-20,1,3992,James Harden,PHL,ACTIVE,UT
1,2022-12-20,1,4277905,Trae Young,ATL,ACTIVE,G
2,2022-12-20,1,6583,Anthony Davis,LAL,OUT,IR
3,2022-12-20,1,4395628,Zion Williamson,NOP,ACTIVE,BE
4,2022-12-20,1,3102531,Kristaps Porzingis,WAS,OUT,PF
...,...,...,...,...,...,...,...
107,2023-01-14,8,6442,Kyrie Irving,BKN,ACTIVE,BE
108,2023-01-14,8,4066636,Markelle Fultz,ORL,ACTIVE,BE
109,2023-01-14,8,4066211,Robert Williams III,BOS,ACTIVE,UT
110,2023-01-14,8,4432158,Evan Mobley,CLE,ACTIVE,F
111,2023-01-14,8,4395630,Devin Vassell,SAS,OUT,IR